import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import CountdownTimer from "@/components/CountdownTimer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const targetDate = new Date('2024-08-31T23:59:59');
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <CountdownTimer targetDate={targetDate} />
      </body>
    </html>
  );
}
